# Site settings
title: SimpleChat-ANF | Azure AI Accelerator
description: Azure AI Accelerator powered by Azure NetApp Files - Enterprise-grade storage for RAG workloads
baseurl: "/simplechat-ANF"
url: "https://DwirefS.github.io"

# Use GitHub Pages default theme
theme: jekyll-theme-primer

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown settings
markdown: kramdown
